/** Laboratory-supplied copy, edited for the web. Keep Japanese and English in sync. */
export type Language = 'ja' | 'en';

const ja = {
  university: '東京理科大学', faculty: '創域情報学部 情報理工学科',
  title: ['AIを「使う」から', '「創る」へ。'],
  intro: '小さく、賢く、自律的に動くAIを。',
  description: 'モデルの設計から学習、評価、社会実装まで。',
  primary: '研究を知る', secondary: '配属を考えている方へ',
  skip: '本文へ移動', menu: 'メニュー', theme: 'ダークテーマ',
  pause: 'アニメーションを一時停止', play: 'アニメーションを再生', top: 'ページ上部へ',
  focus: '小型生成AI ／ 自律分散AI ／ ゲーム・インタラクティブシステム',
  aboutTitle: ['自分の手でつくり、', '動かして、深く知る。'],
  about: '芦原・倉林研究室は、東京理科大学 創域情報学部 情報理工学科の研究室です。多様なシステムと連携しながら、スマートフォンやPC上で動作する、小型・高効率な自律分散型AIを研究します。',
  aboutNote: '中規模データによる学習、公共GPUクラスタでの分散学習、データ自動合成を組み合わせ、用途に特化した国産生成AIの開発を目指します。自ら実装したモデルをゲームなどの体験型システムへ応用し、AIを創る力を育てます。',
  ethics: '無断収集した著作物に依存せず、学習データの権利と出所に配慮した、倫理的で安全なAIの構築を目指します。',
  pillarsTitle: '教育と研究の、三本柱。',
  pillars: [
    { label: 'モデルを自らつくる', title: '生成AIを、フルスクラッチで。', description: '独自実装の小型Transformerや、公開予定の潜在拡散モデルを土台に、自分のモデルを設計・実装します。産業界で使える、小型で実用的な生成AIを追究します。' },
    { label: '研究と実践', title: '研究と実務の、両方から学ぶ。', description: 'Cygamesの取締役CTOと研究所長が直接指導。大規模サービス運営とAI研究の知見をもとに、モデル設計、学習基盤、評価、社会実装を一貫して学びます。' },
    { label: '国内外との共同研究', title: '研究を、世界につなぐ。', description: 'カリフォルニア大学サンディエゴ校、東京藝術大学、東京科学大学、慶應義塾大学などとの共同研究に参加。国内外の研究者と協働し、国際会議への論文投稿を目指します。' },
  ],
  researchTitle: '小さなモデルから、\n新しい体験へ。',
  researchIntro: '以下は、学部生が取り組める研究テーマの一例です。自分が探究したい問いを考える参考にしてください。',
  research: [
    { label: '小型言語モデル', title: '小型Transformer', description: '軽量なモデルによるゲーム内キャラクターの行動・対話を研究します。プレイログから難易度や離脱要因を推定し、ゲームバランスや体験の改善にもつなげます。' },
    { label: 'データと画像生成', title: '小規模データからの画像生成', description: '無断収集データに依存せず、権利と出所を確認した中規模データや自動合成データを活用。限られたデータから高品質な画像を生成するモデルを探究します。' },
    { label: '世界モデル', title: 'ワールドモデルと対話的AI', description: '潜在拡散モデルなどを用い、映像・画像・行動系列から世界の変化を予測。ゲームに応用できる世界理解モデルとインタラクティブAIの構築を目指します。' },
  ],
  computeTitle: '学習を支える計算基盤',
  computeText: '産総研のABCI 3.0や、東京科学大学のTSUBAME 4.0など、公共のスーパーコンピュータを活用します。分散学習から体験型システムへの実装までを研究の対象とします。',
  projectsTitle: 'これまでの研究から',
  projectsIntro: 'AI、ゲーム、インタラクションをつなぐ研究事例。研究室での問いを広げる、これまでの取り組みを紹介します。',
  projects: [
    { name: 'Kinetics', label: 'インタラクション', title: '指の傾きで操作するゲームパッド', description: '指を傾ける動作で操作できる、画面上のゲームパッドの数理モデル。タッチ操作の新しい可能性を探る研究です。', publications: ['publication-20'] },
    { name: 'Cymotion', label: 'キャラクターアニメーション', title: '環境に応じて動くキャラクター', description: '地形やNPCなどの文脈に応じてモーションクリップを検索・合成し、キャラクターの行動を自動で選択する、次世代のアニメーションシステムです。', publications: ['publication-09', 'publication-10'] },
    { name: 'Learned PRNG', label: '生成モデル', title: 'ニューラルネットワークで乱数をつくる', description: '既存の乱数からWGAN-GPで生成器を学習し、NISTテストスイートを通過する乱数を生成。アルゴリズムを手作業で設計する方法に加え、学習による乱数生成を探究します。', publications: ['publication-08'] },
    { name: 'Sketch2Map', label: '創造性支援', title: '手描きスケッチをゲームマップへ', description: '2段階のpix2pix cGANを用いて、手描きのスケッチからゲームマップを自動生成するシステム。ゲームへの深層学習の応用例として、書籍『Deep Learning in Gaming and Animations』でも紹介されています。', publications: ['publication-17'] },
    { name: 'Rayauth', label: '画像認識・認証', title: '光の変化を、真贋判定の手がかりに', description: 'カードのホログラムや透明インクの凹凸が生む、時空間的な光の変化を学習。スマートフォンのカメラで、本物・偽物・画面上のカードを見分け、埋め込みチップに頼らない認証を目指します。', publications: ['publication-02'] },
  ],
  relatedPaper: '関連論文',
  peopleTitle: '研究と実装をつなぐ、ふたり。',
  peopleIntro: '産業の現場と学術研究の両方から、AIを創るプロセスを指導します。',
  people: [
    { name: '芦原 栄登士', englishName: 'Eitoshi Ashihara', role: '客員教授', email: 'ashihara@rs.tus.ac.jp', positions: ['株式会社Cygames 取締役CTO', '株式会社Cygames AI Studio 代表取締役'], specialty: 'プログラミング言語処理系', bio: '東京理科大学卒業後、ゲーム業界でキャリアを開始。ネットワークゲーム開発、基盤構築・運用、技術組織マネジメントに従事。現在はCygamesの研究、インフラ、開発・運用を含むゲーム技術全般を統括する。Cygames AI Studioでは、生成AI時代の価値創出を支える技術基盤と事業戦略を牽引。' },
    { name: '倉林 修一', englishName: 'Shuichi Kurabayashi', role: '教授', email: 'shuichi@rs.tus.ac.jp', positions: ['株式会社Cygames 技術顧問／Cygames Research 所長', '株式会社Cygames AI Studio 取締役CRO'], specialty: 'ビッグデータ処理技術、生成AI、UI技術', bio: '1979年生まれ。慶應義塾大学大学院政策・メディア研究科博士課程修了。博士（政策・メディア）。同大学環境情報学部専任講師を経て、2015年よりCygames。2026年より東京理科大学創域情報学部教授を兼任。研究者として、データ処理から生成AI、インターフェースまでを横断する。' },
  ],
  specialtyLabel: '専門分野', biography: 'プロフィール',
  publicationsTitle: '論文・研究業績',
  publicationsIntro: '研究室の研究につながる関連業績を、過去の取り組みも含めて紹介します。論文タイトル・著者名は原文表記です。',
  publicationLink: '論文・発表を読む', forthcoming: '掲載予定',
  showPublications: 'すべての業績を見る', hidePublications: '一覧を閉じる',
  studentsTitle: ['つくる力を、', '研究する力へ。'],
  studentsIntro: '自分で設計し、実装し、学習し、評価する。そして、動くシステムとしてまとめる。既存のAIを利用する、その先へ進みたい皆さんを歓迎します。',
  studentsLink: 'よくある不安への回答',
  skillsTitle: 'この研究室で身につける、4つの力。',
  skills: [
    { label: '設計', title: 'モデルを創る', description: '小型Transformerや潜在拡散モデルを題材に、ニューラルネットワークの構造を理解し、自ら実装・改良します。' },
    { label: '学習', title: '学習を回す', description: 'データ自動合成や公共GPUクラスタでの分散学習を経験し、研究を最後まで進める実践力を養います。' },
    { label: '評価', title: '多面的に評価する', description: '精度に加え、軽量性、応答速度、再現性、使いやすさまで含め、AIシステムの価値を確かめます。' },
    { label: '協働', title: '協働して成果を出す', description: '教員、学生、他大学や研究機関の研究者と議論し、それぞれの知見を持ち寄って研究を前に進めます。' },
  ],
  fitTitle: '試行錯誤を、面白がれる人へ。',
  fitIntro: '才能よりも、継続して試す力、自分で考えて動く力、面白がる力を重視します。',
  fit: ['分からない数式やコードをそのままにせず、調べ、実験し、少しずつ理解を深められる。', 'AIが「なぜ動くのか」「どう作るのか」に関心を持ち、学問として深く踏み込みたい。', 'ゲーム、画像生成、創造性支援、最適化など、分野を横断して新しいものをつくりたい。', '一人で完結するだけでなく、他者と議論し、共同で前に進むことを楽しめる。'],
  requiredTitle: '入室時に求めること',
  required: [
    { title: 'Pythonの基礎', description: '簡単なプログラムが書けること。変数、条件分岐、関数、配列・辞書などを使える状態が望まれます。完璧である必要はありません。' },
    { title: '粘り強く問題を解く姿勢', description: 'エラーや失敗に直面しても、原因を切り分けながら前に進もうとする姿勢を求めます。' },
    { title: '考えを正確に伝え、理解する力', description: '自分の考えを過不足なく言葉にし、相手の意図も正確に理解できる、高い言語化・コミュニケーション能力を重視します。' },
  ],
  notRequiredTitle: '入室後に、身につけていけること',
  notRequired: ['大規模GPUクラスタの運用経験', '国際会議での発表・論文執筆経験', '高度な数学力や完成された専門性', 'ゲーム開発・生成AIモデルの実装経験'],
  notRequiredNote: 'これらの経験は入室時には不要です。興味と継続力を土台に、研究の中で段階的に学んでいきます。',
  lifeTitle: '研究室での日々',
  life: [
    { title: '小さく再現し、自分の問いへ', description: '小さな再現実験や既存実装の読解から入り、自分の問題設定と改良案へと進みます。共同研究先などを訪問し、実際の現場から得られる知見も研究に生かします。' },
    { title: '分からないことを、議論の出発点に', description: 'ゼミでは進捗共有、技術相談、設計レビュー、論文紹介、実験結果の解釈に取り組みます。必要に応じて共同研究先との議論、外部発表、デモ制作へと広げます。' },
  ],
  roadmapTitle: '卒業研究の、成長ロードマップ。',
  roadmapIntro: '4年次の取り組みの目安です。研究テーマや進捗に応じて進めます。',
  roadmap: [
    { season: '4年 春', label: '基礎を学ぶ', title: '研究の土台をつくる', description: '環境構築、Python・PyTorchの基礎、先行研究の読解、既存実装の理解から開始。再現実験と小さな改良を通じて、自分の手で実験を回す力を身につけます。' },
    { season: '4年 夏〜秋', label: '問いを探究する', title: '自分の問いをかたちにする', description: 'テーマを絞り、実験計画を立てます。モデル、データ、評価指標を設計し、試行錯誤を重ねながら研究としての形をつくります。' },
    { season: '4年 秋〜冬', label: '成果を伝える', title: '成果をまとめ、伝える', description: '結果を整理し、卒業研究としてまとめます。内容に応じて、デモ、対外発表、論文投稿にも挑戦します。' },
  ],
  faqTitle: 'はじめの一歩の、その前に。',
  faqIntro: '配属を考えるときの、よくある不安に答えます。',
  faq: [
    { question: '数学が得意でないと、難しいですか？', answer: '最初から得意である必要はありません。研究で必要になったところを、実装と結びつけながら学んでいきます。分からないことを放置せず、少しずつ理解を深める姿勢を大切にしています。' },
    { question: '英語の論文を読めるか、不安です。', answer: '最初は誰でも負荷を感じるものです。いきなり完璧に読むことを目指さず、重要な図、式、実験設定を押さえながら、少しずつ読み進めていきましょう。' },
    { question: '生成AIを使ったことはありますが、作った経験がありません。', answer: 'まさに、その段階の学生を対象としています。Pythonの基礎を足がかりに、モデルを設計・実装・学習する経験を積み、AIの利用者から開発者へ進むことを重視します。' },
    { question: '自分に研究が向いているか分かりません。', answer: '最初から研究者らしくある必要はありません。小さく作り、小さく確かめ、少しずつ深めていく中で、自分に合ったテーマや進め方を見つけていきます。' },
  ],
  contactTitle: '研究室への相談・お問い合わせ',
  contactText: '研究内容や配属、共同研究についてのご相談は、お問い合わせフォームをご利用ください。',
};

const en: typeof ja = {
  university: 'Tokyo University of Science', faculty: 'Faculty & Department of Information Science and Technology',
  title: ['From using AI', 'to creating it.'],
  intro: 'Small, efficient AI that acts autonomously.',
  description: 'Design, train, evaluate—and bring your models to life.',
  primary: 'Explore our research', secondary: 'For prospective students',
  skip: 'Skip to content', menu: 'Menu', theme: 'Dark theme',
  pause: 'Pause animation', play: 'Play animation', top: 'Back to top',
  focus: 'Small generative models / Autonomous distributed AI / Games & interactive systems',
  aboutTitle: ['Build it. Run it.', 'Understand it.'],
  about: 'Ashihara-Kurabayashi Lab. is part of the Department of Information Science and Technology, Faculty of Information Science and Technology, at Tokyo University of Science. We study small, efficient, autonomous distributed AI that runs on smartphones and PCs while working with other systems.',
  aboutNote: 'We combine training on medium-sized datasets, distributed learning on public GPU clusters, and automated data synthesis to develop specialized generative AI in Japan. By integrating our own models into games and other interactive experiences, we help students learn to create AI.',
  ethics: 'We aim to build ethical, safe AI with attention to data rights and provenance, without relying on copyrighted works collected without permission.',
  pillarsTitle: 'Three pillars of learning and research.',
  pillars: [
    { label: 'BUILD FROM SCRATCH', title: 'Create your own generative AI.', description: 'Design and implement models using our small Transformer implementations and latent diffusion models planned for release. Explore compact, practical generative AI with applications in industry.' },
    { label: 'RESEARCH MEETS PRACTICE', title: 'Learn from research and industry.', description: 'Receive direct guidance from the CTO of Cygames and the director of Cygames Research. Connect model design, training infrastructure, evaluation, and deployment through experience in AI research and large-scale services.' },
    { label: 'GLOBAL COLLABORATION', title: 'Connect your research to the world.', description: 'Participate in collaborations with institutions including UC San Diego, Tokyo University of the Arts, Institute of Science Tokyo, and Keio University. Work with researchers in Japan and abroad, with the aim of submitting to international conferences.' },
  ],
  researchTitle: 'Small models.\nNew experiences.',
  researchIntro: 'These are examples of topics available to undergraduate researchers. Use them as starting points for the questions you want to explore.',
  research: [
    { label: 'SMALL TRANSFORMERS', title: 'Small Transformers', description: 'Explore lightweight models for the actions and dialogue of game characters. Learn from play logs to estimate difficulty and reasons for player dropout, informing game balance and player experience.' },
    { label: 'DATA-CONSCIOUS GENERATION', title: 'Image generation with limited data', description: 'Investigate high-quality image generation using medium-sized datasets with verified rights and provenance, alongside synthesized data, without relying on unauthorized data collection.' },
    { label: 'WORLD MODELS', title: 'World models & interactive AI', description: 'Use approaches such as latent diffusion to predict changes in the world from video, images, and action sequences. Develop predictive and world-understanding models for games and interactive AI.' },
  ],
  computeTitle: 'Computing infrastructure for learning',
  computeText: 'We use public supercomputers such as ABCI 3.0 at AIST and TSUBAME 4.0 at Institute of Science Tokyo. Our research connects distributed training with implementation in interactive systems.',
  projectsTitle: 'Research in practice',
  projectsIntro: 'Examples connecting AI, games, and interaction. These previous projects offer starting points for new research questions.',
  projects: [
    { name: 'Kinetics', label: 'INTERACTION', title: 'A gamepad controlled by finger tilting', description: 'A mathematical model for an on-screen gamepad controlled by tilting a finger, exploring new possibilities for touch interaction.', publications: ['publication-20'] },
    { name: 'Cymotion', label: 'CHARACTER ANIMATION', title: 'Characters that respond to their surroundings', description: 'A next-generation animation system that retrieves and blends motion clips based on context, such as terrain and NPCs, to automatically select suitable character actions.', publications: ['publication-09', 'publication-10'] },
    { name: 'Learned PRNG', label: 'GENERATIVE MODELS', title: 'Learning to generate random numbers', description: 'Train a generator from existing random numbers using WGAN-GP to produce outputs that pass the NIST test suite. Explore learned random number generation alongside manually designed algorithms.', publications: ['publication-08'] },
    { name: 'Sketch2Map', label: 'CREATIVITY SUPPORT', title: 'From a hand-drawn sketch to a game map', description: 'A two-stage pix2pix conditional GAN system that turns hand-drawn sketches into game maps. The work is also featured in the book Deep Learning in Gaming and Animations as an application of deep learning to games.', publications: ['publication-17'] },
    { name: 'Rayauth', label: 'VISION & AUTHENTICATION', title: 'Authenticating cards through changing light', description: 'Learn spatiotemporal changes in light caused by holograms and transparent ink structures on cards. Use a smartphone camera to distinguish genuine cards, counterfeits, and screen displays, exploring authentication without embedded chips.', publications: ['publication-02'] },
  ],
  relatedPaper: 'Related paper',
  peopleTitle: 'Connecting research and implementation.',
  peopleIntro: 'Learn the process of creating AI through experience in both academic research and industry.',
  people: [
    { name: 'Eitoshi Ashihara', englishName: '芦原 栄登士', role: 'Visiting Professor', email: 'ashihara@rs.tus.ac.jp', positions: ['Director & CTO, Cygames, Inc.', 'Representative Director, Cygames AI Studio, Inc.'], specialty: 'Programming language implementation', bio: 'After graduating from Tokyo University of Science, he began his career in games, working on network game development, infrastructure, operations, and technical organization management. At Cygames, he oversees game technology spanning research, infrastructure, development, and operations. At Cygames AI Studio, he leads the technical foundations and business strategy for creating value in the generative AI era.' },
    { name: 'Shuichi Kurabayashi', englishName: '倉林 修一', role: 'Professor', email: 'shuichi@rs.tus.ac.jp', positions: ['Technical Advisor, Cygames, Inc. / Director, Cygames Research', 'Director & CRO (Chief Research Officer), Cygames AI Studio, Inc.'], specialty: 'Big data processing, generative AI, and user interfaces', bio: 'Born in 1979. He earned his doctorate from the Graduate School of Media and Governance at Keio University. After serving as a full-time lecturer in its Faculty of Environment and Information Studies, he joined Cygames in 2015. Since 2026, he has also held a professorship at Tokyo University of Science, working across data processing, generative AI, and user interfaces.' },
  ],
  specialtyLabel: 'Research interests', biography: 'Biography',
  publicationsTitle: 'Publications & research',
  publicationsIntro: 'Related work that informs our research, including projects from previous years. Publication titles and author names are retained in their original language.',
  publicationLink: 'Read the publication', forthcoming: 'To appear',
  showPublications: 'View all publications', hidePublications: 'Collapse the list',
  studentsTitle: ['From making things', 'to making discoveries.'],
  studentsIntro: 'Design, implement, train, and evaluate your own models—and turn them into working systems. We welcome students who want to go beyond using existing AI.',
  studentsLink: 'Read the FAQs',
  skillsTitle: 'Four capabilities to develop here.',
  skills: [
    { label: 'DESIGN', title: 'Build models', description: 'Understand neural network architectures through small Transformers and latent diffusion models, then implement and improve them yourself.' },
    { label: 'TRAIN', title: 'Run training', description: 'Gain practical experience with automated data synthesis and distributed learning on public GPU clusters, developing the skills to carry research through.' },
    { label: 'EVALUATE', title: 'Evaluate from multiple perspectives', description: 'Assess not only accuracy, but also model size, response time, reproducibility, and usability to understand the value of an AI system.' },
    { label: 'COLLABORATE', title: 'Achieve results together', description: 'Discuss ideas with faculty, students, and researchers at other institutions. Bring different perspectives together to move research forward.' },
  ],
  fitTitle: 'For people who enjoy trial and error.',
  fitIntro: 'We value persistence, independent thinking, initiative, and curiosity more than innate talent.',
  fit: ['You investigate unfamiliar mathematics or code, experiment, and deepen your understanding step by step.', 'You want to understand why AI works and how to build it, engaging with the subject as a field of study.', 'You want to create across fields such as games, image generation, creativity support, and optimization.', 'You enjoy discussing ideas and making progress with others, as well as working independently.'],
  requiredTitle: 'What we ask you to bring',
  required: [
    { title: 'Basic Python skills', description: 'Be able to write simple programs using variables, conditionals, functions, lists, and dictionaries. You do not need to know everything.' },
    { title: 'Persistence in solving problems', description: 'Be willing to investigate errors and failures, isolate their causes, and keep moving forward.' },
    { title: 'Clear expression and careful understanding', description: 'We place a strong emphasis on articulating your ideas precisely and fully, while accurately understanding what others mean.' },
  ],
  notRequiredTitle: 'What you can learn after joining',
  notRequired: ['Operating large GPU clusters', 'Presenting at international conferences and writing papers', 'Advanced mathematics or fully developed expertise', 'Game development or implementing generative AI models'],
  notRequiredNote: 'You do not need these experiences before joining. With curiosity and persistence, you will build them gradually through research.',
  lifeTitle: 'Life in the lab',
  life: [
    { title: 'From small reproductions to your own questions', description: 'Begin by reproducing experiments and reading existing implementations, then develop your own problem statements and improvements. Visits to research collaborators also bring knowledge from real-world practice into your work.' },
    { title: 'Let questions start the conversation', description: 'Seminars include progress updates, technical discussions, design reviews, paper reading, and interpretation of experiments. Where appropriate, the work extends to partner discussions, external presentations, and demonstrations.' },
  ],
  roadmapTitle: 'Your path through undergraduate research.',
  roadmapIntro: 'A guide to the fourth year. The pace and activities depend on your research topic and progress.',
  roadmap: [
    { season: 'Year 4 · Spring', label: 'FOUNDATIONS', title: 'Build your foundations', description: 'Set up your environment, learn Python and PyTorch fundamentals, read prior work, and study existing implementations. Reproduce experiments and make small improvements until you can run your own investigations.' },
    { season: 'Year 4 · Summer–Autumn', label: 'EXPLORATION', title: 'Shape your own question', description: 'Narrow your topic and plan experiments. Design models, datasets, and evaluation criteria, iterating until your ideas take shape as a research project.' },
    { season: 'Year 4 · Autumn–Winter', label: 'COMMUNICATION', title: 'Bring your findings together', description: 'Analyze your results and complete your graduation research. Depending on the work, explore demonstrations, external presentations, and paper submissions.' },
  ],
  faqTitle: 'Before your first step.',
  faqIntro: 'Answers to common concerns about joining the lab.',
  faq: [
    { question: 'Do I need to be good at mathematics?', answer: 'You do not need to be an expert at the start. You will learn the mathematics your research requires by connecting it with implementation. What matters is a willingness to investigate and gradually understand unfamiliar ideas.' },
    { question: 'I am worried about reading papers in English.', answer: 'Most people find it demanding at first. Rather than aiming for perfect understanding immediately, begin with the important figures, equations, and experimental settings, and build your reading skills over time.' },
    { question: 'I have used generative AI, but never built it.', answer: 'That is exactly the stage we welcome. Starting with basic Python skills, you will gain experience designing, implementing, and training models. Our focus is helping you progress from an AI user to an AI developer.' },
    { question: 'How do I know whether research is right for me?', answer: 'You do not have to arrive thinking like an experienced researcher. By building small things, testing ideas, and gradually going deeper, you can discover topics and ways of working that suit you.' },
  ],
  contactTitle: 'Get in touch with the lab',
  contactText: 'For enquiries about research, joining the lab, or collaborations, please use our contact form.',
};

export const copy: Record<Language, typeof ja> = { ja, en };
export type SiteContent = typeof ja;
